# Generated by Django 5.1.6 on 2025-02-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchasestatus',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='rental',
            name='rentalstatus',
            field=models.IntegerField(default=0),
        ),
    ]
