# Generated by Django 5.1.6 on 2025-02-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_purchase_purchasestatus_rental_rentalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rentalstatus',
        ),
    ]
