# Generated by Django 5.1.6 on 2025-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_remove_rental_rentalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
