# Generated by Django 5.1.6 on 2025-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchasestatus',
            field=models.IntegerField(default=0),
        ),
    ]
