# Generated by Django 5.1.6 on 2025-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_rename_notification_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
