# Generated by Django 5.1.6 on 2025-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_rental_viewed_delete_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='viewed',
            new_name='aviewed',
        ),
        migrations.AddField(
            model_name='rental',
            name='uviewed',
            field=models.IntegerField(default=0),
        ),
    ]
